"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from .logging import LOGGING
import os
from celery.schedules import crontab

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url

from .utils import env_bool

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Telegram app settings
TELEGRAM_API_ID = os.getenv('TELEGRAM_API_ID')
TELEGRAM_API_HASH = os.getenv('TELEGRAM_API_HASH')
TELEGRAM_SESSION_STRING = os.getenv('TELEGRAM_SESSION_STRING')

# Telegram settings check
# SESSIONS_STRING is not necessary, because working with sole db can be too
if not TELEGRAM_API_ID or not TELEGRAM_API_HASH:
    raise ImproperlyConfigured(
        "Нет конфигурации для Telegram API. "
        "Установи TELEGRAM_API_ID, TELEGRAM_API_HASH"
    )

# Celery settings
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Redis like messages brocker
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"  # tasks results
CELERY_ACCEPT_CONTENT = ["json"]  # tasks data format
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Moscow"  # project timezone

# Celery dict with schedule
CELERY_BEAT_SCHEDULE = {
    "parse-all-channels-every-day-12-30": {
        "task": "config.parser.tasks.parse_all_channels",  # path to task
        "schedule": crontab(hour=11, minute=40),
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guardian',
    
    'inertia',

    'widget_tweaks',
    'django_bootstrap5',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'config',
    'apps.users',
    'apps.group_channels',
    'apps.parser',
    'apps.homepage',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
]

SITE_ID = 1

# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
# ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # или 'mandatory'
LOGIN_REDIRECT_URL = '/'  # Куда перенаправлять после входа

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'inertia.middleware.InertiaMiddleware',
    'apps.users.middleware.RoleMiddleware',
]



MAPPING_PROD = {
    'f':'https://localhost:8000/accounts/yandex/login/callback/',
    't':'https://hexlet-price-tracker-8znh.onrender.com/accounts/yandex/login/callback/'
}

SOCIALACCOUNT_PROVIDERS = {
    'yandex': {
        'APP': {
            'secret': os.getenv('SECRET_ID_YA'),
            'client_id': os.getenv('CLIENT_ID_YA'),
            'redirect_uri': MAPPING_PROD.get(os.getenv('PROD')), 
        },
        'SCOPE': [
            'login:email',   # Доступ к email
            'login:info',     # Основная информация (имя, фамилия)
            'login:avatar',   # Аватар пользователя
        ],
        'AUTH_PARAMS': {
            'force_confirm': True,  # Всегда запрашивать подтверждение прав
        }
    }
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('PROD') == 't':
    DATABASES = {
        'default':{
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('NAMEDB'),
            'USER': os.getenv('USERDB'),
            'PASSWORD': os.getenv('PASSWORDDB'),
            'HOST': os.getenv('HOSTDB'),
            'PORT': os.getenv('PORTDB'),
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3'),
            conn_max_age=600
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

if os.getenv('PROD') == 't':
    # ALLOWED_HOSTS = ['example.com']
    # will configure SMTP in future
    ...
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    # Email settings for development - emails will be printed to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    

# Inertia settings    
    
INERTIA_LAYOUT = "base.html"
CSRF_HEADER_NAME = 'HTTP_X_XSRF_TOKEN'
CSRF_COOKIE_NAME = 'XSRF-TOKEN'

# При переходе на инерцию раскоментировать 
# STATICFILES_DIRS = [
#    BASE_DIR / "frontend" / "public",
#]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
